# Name the node stage "builder"
FROM node:18.16.0 AS base
# Set working directory
FROM base AS deps
WORKDIR /app
# install node modules and build assets
CMD set NODE_OPTIONS=--max_old_space_size=8192
COPY package.json  ./
RUN npm i 

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build 

FROM base AS runner
WORKDIR /app

# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nextjs


COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing

# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# USER nextjs

ENTRYPOINT ["npm", "run","start"]