import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { getBlogs, getHospitals, getProcedures } from '@/functions';
import { useEffect, useState, useRef } from 'react';
import Blog from '@/components/Blog';
import { useTranslation } from 'react-i18next';
import Hospital from '@/components/Hospital';
import CalendarComponent from '@/components/Calendar';
import Cities from '@/components/Cities';
import moment from 'moment';
import { useRouter } from 'next/router';
import HospitalModals from '@/components/HospitalsModal';
export default function Home() {
  const router = useRouter();
  const handleClick = () => {
    const myObj = {
      key: 'lokman',
      location,
      choosenDistrictId,
      chooseCity,
      choosenLocation,
    };
    const encodedObj = encodeURIComponent(JSON.stringify(myObj));
    router.push(`http://klinik.klinikya.com/global-search?obj=${encodedObj}`);
  };
  const [procedures, setProcedures] = useState<any>();
  const [blogs, setBlogs] = useState<any>();
  const [hospitals, setHospitals] = useState<any>();
  const [dateFrom, setDateFrom] = useState<Date | undefined>(undefined);
  const [dateTo, setDateTo] = useState<Date | undefined>(undefined);
  const [key, setKey] = useState<string>('');
  const [choosenDistrictId, setChoosenDistrictId] = useState(null);
  const [chooseCity, setChooseCity] = useState();
  const [choosenLocation, setChoosenLocation] = useState(undefined);
  const [location, setLocation] = useState<any>();

  const { t } = useTranslation();
  useEffect(() => {
    getProcedures(setProcedures);
    getBlogs(setBlogs);
    getHospitals(setHospitals);
  }, []);

  const hospitalArr = hospitals?.filter(
    (item: any) =>
      item?.Id === 5 ||
      item?.Id === 51 ||
      item?.Id === 46 ||
      item?.Id === 128 ||
      item?.Id === 14 ||
      item?.Id === 53 ||
      item?.Id === 12 ||
      item?.Id === 152 ||
      item?.Id === 19 ||
      item?.Id === 147
  );
  const [start, setStart] = useState(0);
  const [end, setEnd] = useState(4);
  const handleView = (a: number, b: number) => {
    setStart(a);
    setEnd(b);
  };
  const [showModal, setShowModal] = useState(false);

  const handleClick2 = (id: number) => {
    router.push(`http://klinik.klinikya.com/hospital-details?id=53`);
  };
  const departments = useRef(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;0,1000;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900;1,1000&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        {/* <div onClick={() => handleClick2(53)}>deneme</div>
        <div onClick={() => handleClick()}>deneme2</div> */}
        {showModal && (
          <HospitalModals hospitals={hospitals} setShowModal={setShowModal} />
        )}
        <section className={styles.partOneWrapper}>
          <div className={styles.partOneTop}>
            <div className={styles.partOneTopLeft}>
              <h1>{t('MainHeading')}</h1>
              <p className={`${'text18'}`}>{t('MainText')}</p>
              <button className={styles.button}>{t('button')}</button>
            </div>
            <img
              src="/icons/illustration.svg"
              alt="health-team"
              className={styles.partOneTopRight}
            />
          </div>
          <div className={styles.searchWrapper}>
            <div className={styles.searchWrapperInside}>
              <img src="/icons/search.svg" alt="search" />
              <input
                type="text"
                placeholder={t('SearchBar1') as string | undefined}
                onChange={(e) => setKey(e.target.value)}
                className={styles.input}
              />
            </div>
            <div className={styles.line}></div>
            <div className={styles.searchWrapperInside}>
              <img src="/icons/location.svg" alt="location" />
              <Cities
                setChoosenDistrictId={setChoosenDistrictId}
                setChoosenLocation={setChoosenLocation}
                setChooseCity={setChooseCity}
                setLocation={setLocation}
                location={location}
              />
            </div>
            <div className={styles.line}></div>
            <div className={styles.searchWrapperInside}>
              <img src="/icons/calendar.svg" alt="calendar" />

              <CalendarComponent />
            </div>
            <div onClick={handleClick} className={styles.buttonSearch}>
              <img src="/icons/search-white.svg" alt="search" />
              <p>{t('search')}</p>
            </div>
          </div>
        </section>
        <section className={styles.partTwoWrapper}>
          <div>
            <h1 className={styles.title}>{t('HealthPackagesTitle')}</h1>
            <p className={styles.procedureText}>{t('HealthPackagesText')}</p>
          </div>
          <div className={styles.procedures}>
            {procedures?.slice(0, 4)?.map((item: any) => (
              <div className={styles.boxWrapper}>
                <div className={styles.boxWrapperTop}>
                  <img
                    src={item?.Hospital?.SmallLogoLocation}
                    alt="hospital-logo"
                    className={styles.imageHospital}
                  />
                  <div>
                    <p className={styles.operation}>{item?.Operation?.Name}</p>
                    <p className={styles.hospital}>{item?.Hospital?.Name}</p>
                  </div>
                </div>
                <div className={styles.longLine}></div>
                <p className={styles.description}>{item?.Description}</p>
                <div>
                  <div className={styles.view}>{t('view')}</div>
                  <img src="/icons/Arrow.svg" alt="arrow" />
                </div>
              </div>
            ))}
          </div>
        </section>
        <section className={styles.partThreeWrapper} ref={departments}>
          <h1 className={styles.title}>{t('departments')}</h1>
          <p className={styles.departmentsText}>{t('departmentsText')}</p>
          <div className={styles.departments}>
            <div className={styles.department}>
              <img src="/icons/womanHealth.svg" alt="womanHealth" />
              <p className={styles.departmentTitle}>{t('womensHealth')}</p>
              <p className={styles.departmentText}>{t('womensHealthText')}</p>
            </div>
            <div className={styles.department}>
              <img src="/icons/oncology.svg" alt="oncology" />
              <p className={styles.departmentTitle}>{t('Oncology')}</p>
              <p className={styles.departmentText}>{t('OncologyText')}</p>
            </div>
            <div className={styles.department}>
              <img src="/icons/romatology.svg" alt="romatology" />
              <p className={styles.departmentTitle}>{t('Rheumatology')}</p>
              <p className={styles.departmentText}>{t('RheumatologyText')}</p>
            </div>
            <div className={styles.department}>
              <img src="/icons/estetic.svg" alt="estetic" />
              <p className={styles.departmentTitle}>{t('AestheticSurgery')}</p>
              <p className={styles.departmentText}>
                {t('AestheticSurgeryText')}
              </p>
            </div>
            <div className={styles.department}>
              <img src="/icons/teeth.svg" alt="teeth" />
              <p className={styles.departmentTitle}>{t('teeth')}</p>
              <p className={styles.departmentText}>{t('teethText')}</p>
            </div>
            <div className={styles.department}>
              <img src="/icons/norology.svg" alt="norology" />
              <p className={styles.departmentTitle}>{t('Neurology')}</p>
              <p className={styles.departmentText}>{t('NeurologyText')}</p>
            </div>
            <div className={styles.department}>
              <img src="/icons/medicine.svg" alt="medicine" />
              <p className={styles.departmentTitle}>{t('InternalMedicine')}</p>
              <p className={styles.departmentText}>
                {t('InternalMedicineText')}
              </p>
            </div>
            <div className={styles.department}>
              <img src="/icons/obesity.svg" alt="obesity" />
              <p className={styles.departmentTitle}>{t('Obesity')}</p>
              <p className={styles.departmentText}>{t('ObesityText')}</p>
            </div>
          </div>
        </section>
        <section className={styles.partFourWrapper}>
          <h1 className={styles.title}>{t('Hospitals')}</h1>
          <p className={styles.departmentsText}>{t('HospitalsText')}</p>
          <div className={styles.hospitalsWrapper}>
            <div className={styles.hospitals}>
              {hospitalArr?.slice(start, end)?.map((item: any) => (
                <Hospital item={item} />
              ))}
            </div>
          </div>
          <div className={styles.dots}>
            <img
              src={
                start === 0
                  ? '/icons/Ellipse 145.svg'
                  : '/icons/Ellipse 146.svg'
              }
              alt="Ellipse"
              onClick={() => handleView(0, 4)}
            />
            <img
              src={
                start === 4
                  ? '/icons/Ellipse 145.svg'
                  : '/icons/Ellipse 146.svg'
              }
              alt="Ellipse"
              onClick={() => handleView(4, 8)}
            />
            <img
              src={
                start === 8
                  ? '/icons/Ellipse 145.svg'
                  : '/icons/Ellipse 146.svg'
              }
              alt="Ellipse"
              onClick={() => handleView(8, 10)}
            />
          </div>
          <button
            onClick={() => setShowModal(true)}
            className={styles.viewHospital}
          >
            {t('showAllHospitals')}
          </button>
        </section>
        <section className={styles.partFiveWrapper}>
          <h1 className={styles.title}>{t('blog')}</h1>
          <p className={styles.blogText}>{t('BlogText')}</p>
          <div className={styles.blogs}>
            {blogs?.slice(0, 3)?.map((item: any) => (
              <Blog item={item} />
            ))}
          </div>
          <div className={styles.viewHospital}>{t('showAllBlogs')}</div>
        </section>
      </main>
    </>
  );
}
